#!/bin/bash

# create-k8s-namespaces.sh
# Unified Kubernetes namespace creation script that adapts based on SCENARIO variable
# Supports:
#   SCENARIO=1: 1 namespace (cluster 1)
#   SCENARIO=2: 2 namespaces (clusters 1 and 2)
#   SCENARIO=3: 3 namespaces (clusters 1, 2, and 3)

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default configuration file
CONFIG_FILE="env-config.sh"

# Parse command line options
parse_options() {
    local TEMP
    TEMP=$(getopt -o c: --long config: -n 'create-k8s-namespaces.sh' -- "$@")

    if [ $? != 0 ]; then
        echo "Usage: $0 [-c config-file]" >&2
        exit 1
    fi

    eval set -- "$TEMP"

    while true; do
        case "$1" in
            -c|--config)
                CONFIG_FILE="$2"
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "Internal error!" >&2
                exit 1
                ;;
        esac
    done
}

# Load configuration file
load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        echo -e "${YELLOW}Error: Configuration file not found: $CONFIG_FILE${NC}"
        echo ""
        echo "Please ensure $CONFIG_FILE exists or run previous setup scripts first"
        exit 1
    fi

    echo -e "${BLUE}Loading configuration from: $CONFIG_FILE${NC}"
    source "$CONFIG_FILE"
    echo ""
}

# Validate scenario and set cluster configuration
validate_scenario() {
    if [ -z "$SCENARIO" ]; then
        echo -e "${YELLOW}Error: SCENARIO variable not set in $CONFIG_FILE${NC}"
        echo "Please set SCENARIO=1, 2, or 3"
        exit 1
    fi

    case "$SCENARIO" in
        1)
            LOCAL_CLUSTERS="1"
            EXTERNAL_CLUSTERS=""
            echo -e "${GREEN}Scenario 1: Creating 1 namespace (local account)${NC}"
            ;;
        2)
            LOCAL_CLUSTERS="1 2"
            EXTERNAL_CLUSTERS=""
            echo -e "${GREEN}Scenario 2: Creating 2 namespaces (local account)${NC}"
            ;;
        3)
            LOCAL_CLUSTERS="1 2"
            EXTERNAL_CLUSTERS="3"
            echo -e "${GREEN}Scenario 3: Creating 3 namespaces (2 local + 1 external)${NC}"
            ;;
        *)
            echo -e "${YELLOW}Error: Invalid SCENARIO value: $SCENARIO${NC}"
            echo "Valid values: 1, 2, or 3"
            exit 1
            ;;
    esac
    echo ""
}

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}  Kubernetes Namespace Setup${NC}"
echo -e "${BLUE}=============================================${NC}"
echo ""

# Validate required environment variables
validate_env() {
    local required_vars=("CLUSTER_NAME" "LOCAL_TASK_ROLE_ARN")

    # Only require external role ARN for scenario 3
    if [ "$SCENARIO" = "3" ]; then
        required_vars+=("EXTERNAL_TASK_ROLE_ARN")
    fi

    for var in "${required_vars[@]}"; do
        if [ -z "${!var}" ]; then
            echo -e "${YELLOW}Error: $var is not defined.${NC}"
            echo ""
            echo "Please ensure $CONFIG_FILE contains this variable"
            echo "or run the previous setup scripts first"
            exit 1
        fi
    done
}

# Set service account names with defaults
set_service_account_names() {
    export LOCAL_ECS_SERVICE_ACCOUNT_NAME=${LOCAL_ECS_SERVICE_ACCOUNT_NAME:-ecs-demo-sa-local}
    export EXTERNAL_ECS_SERVICE_ACCOUNT_NAME=${EXTERNAL_ECS_SERVICE_ACCOUNT_NAME:-ecs-demo-sa-external}

    echo "Configuration:"
    echo "  Scenario: ${SCENARIO}"
    echo "  Cluster Name: ${CLUSTER_NAME}"
    echo "  Local Service Account: ${LOCAL_ECS_SERVICE_ACCOUNT_NAME}"
    if [ "$SCENARIO" = "3" ]; then
        echo "  External Service Account: ${EXTERNAL_ECS_SERVICE_ACCOUNT_NAME}"
    fi
    echo ""
}

# Save service account names to config file
save_to_config() {
    echo -e "${BLUE}Saving service account names to configuration...${NC}"

    # Remove any existing section generated by this script
    if grep -q "# === Generated by create-k8s-namespaces" "$CONFIG_FILE" 2>/dev/null; then
        sed '/# === Generated by create-k8s-namespaces/,/^$/d' "$CONFIG_FILE" > "${CONFIG_FILE}.tmp"
        mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
    fi

    # Append service account names
    cat >> "$CONFIG_FILE" <<EOF

# === Generated by create-k8s-namespaces.sh on $(date) ===
export LOCAL_ECS_SERVICE_ACCOUNT_NAME="$LOCAL_ECS_SERVICE_ACCOUNT_NAME"
EOF

    if [ "$SCENARIO" = "3" ]; then
        cat >> "$CONFIG_FILE" <<EOF
export EXTERNAL_ECS_SERVICE_ACCOUNT_NAME="$EXTERNAL_ECS_SERVICE_ACCOUNT_NAME"
EOF
    fi

    echo "" >> "$CONFIG_FILE"

    echo "✓ Service account names appended to: $CONFIG_FILE"
    echo ""
}

# Function to create namespace for a cluster
create_namespace_for_cluster() {
    local cluster_num=$1
    local task_role_arn=$2
    local svc_account_name=$3
    local account_type=$4

    local namespace="ecs-${CLUSTER_NAME}-${cluster_num}"

    echo -e "${GREEN}Creating namespace for cluster ${cluster_num} (${account_type})...${NC}"

    # Create namespace if it doesn't exist
    if kubectl get ns ${namespace} &>/dev/null; then
        echo "  Namespace ${namespace} already exists"
    else
        kubectl create ns ${namespace}
        echo "  ✓ Namespace ${namespace} created"
    fi

    # Label namespace for ambient mode
    kubectl label namespace ${namespace} istio.io/dataplane-mode=ambient --overwrite
    echo "  ✓ Namespace labeled for ambient mode"

    # Create service account if it doesn't exist
    if kubectl get sa ${svc_account_name} -n ${namespace} &>/dev/null; then
        echo "  Service account ${svc_account_name} already exists"
    else
        kubectl create sa ${svc_account_name} -n ${namespace}
        echo "  ✓ Service account ${svc_account_name} created"
    fi

    # Annotate service account with task role ARN
    kubectl -n ${namespace} annotate sa ${svc_account_name} \
        ecs.solo.io/role-arn=${task_role_arn} \
        --overwrite

    echo "  ✓ Service account annotated with role ARN"
    echo "    Namespace: ${namespace}"
    echo "    Service Account: ${svc_account_name}"
    echo "    Role ARN: ${task_role_arn}"
    echo ""
}

# Main execution
main() {
    parse_options "$@"
    load_config
    validate_scenario
    validate_env
    set_service_account_names

    # Create namespaces for local clusters
    if [ -n "$LOCAL_CLUSTERS" ]; then
        echo -e "${BLUE}Creating namespaces for LOCAL clusters...${NC}"
        echo ""

        for cluster_num in $LOCAL_CLUSTERS; do
            create_namespace_for_cluster "$cluster_num" "$LOCAL_TASK_ROLE_ARN" "$LOCAL_ECS_SERVICE_ACCOUNT_NAME" "local"
        done
    fi

    # Create namespace for external cluster (only for scenario 3)
    if [ -n "$EXTERNAL_CLUSTERS" ]; then
        echo -e "${BLUE}Creating namespace for EXTERNAL cluster...${NC}"
        echo ""

        for cluster_num in $EXTERNAL_CLUSTERS; do
            create_namespace_for_cluster "$cluster_num" "$EXTERNAL_TASK_ROLE_ARN" "$EXTERNAL_ECS_SERVICE_ACCOUNT_NAME" "external"
        done
    fi

    # Save service account names to config
    save_to_config

    echo -e "${GREEN}=============================================${NC}"
    echo -e "${GREEN}  Namespace Setup Complete!${NC}"
    echo -e "${GREEN}=============================================${NC}"
    echo ""
    echo "Created namespaces:"
    for cluster_num in $LOCAL_CLUSTERS; do
        echo "  - ecs-${CLUSTER_NAME}-${cluster_num} (local)"
    done
    for cluster_num in $EXTERNAL_CLUSTERS; do
        echo "  - ecs-${CLUSTER_NAME}-${cluster_num} (external)"
    done
    echo ""
    echo "Service account names saved to: $CONFIG_FILE"
    echo ""
    echo "Verify with:"
    echo "  kubectl get ns | grep ecs-${CLUSTER_NAME}"
    echo "  kubectl get sa -n ecs-${CLUSTER_NAME}-1"
    echo ""
}

# Run main function
main "$@"

# ============================================
# CLEANUP - Prevents shell pollution
# ============================================

unset -f parse_options
unset -f load_config
unset -f validate_scenario
unset -f validate_env
unset -f set_service_account_names
unset -f save_to_config
unset -f create_namespace_for_cluster
unset -f main

unset GREEN BLUE YELLOW NC
unset LOCAL_CLUSTERS EXTERNAL_CLUSTERS

set +e
