#!/bin/bash

# create-k8s-namespaces-3-clusters.sh
# Creates Kubernetes namespaces and service accounts for all 3 ECS clusters

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default configuration file
CONFIG_FILE="env-config.sh"

# Parse command line options
parse_options() {
    local TEMP
    TEMP=$(getopt -o c: --long config: -n 'create-k8s-namespaces-3-clusters.sh' -- "$@")
    
    if [ $? != 0 ]; then
        echo "Usage: $0 [-c config-file]" >&2
        exit 1
    fi
    
    eval set -- "$TEMP"
    
    while true; do
        case "$1" in
            -c|--config)
                CONFIG_FILE="$2"
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "Internal error!" >&2
                exit 1
                ;;
        esac
    done
}

# Load configuration file
load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        echo -e "${YELLOW}Error: Configuration file not found: $CONFIG_FILE${NC}"
        echo ""
        echo "Please ensure $CONFIG_FILE exists or run previous setup scripts first"
        exit 1
    fi
    
    echo -e "${BLUE}Loading configuration from: $CONFIG_FILE${NC}"
    source "$CONFIG_FILE"
    echo ""
}

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}  Kubernetes Namespace Setup${NC}"
echo -e "${BLUE}=============================================${NC}"
echo ""

# Validate required environment variables
validate_env() {
    local required_vars=("CLUSTER_NAME" "LOCAL_TASK_ROLE_ARN" "EXTERNAL_TASK_ROLE_ARN")
    for var in "${required_vars[@]}"; do
        if [ -z "${!var}" ]; then
            echo -e "${YELLOW}Error: $var is not defined.${NC}"
            echo ""
            echo "Please ensure $CONFIG_FILE contains this variable"
            echo "or run the previous setup scripts first"
            exit 1
        fi
    done
}

# Set service account names with defaults
set_service_account_names() {
    export LOCAL_ECS_SERVICE_ACCOUNT_NAME=${LOCAL_ECS_SERVICE_ACCOUNT_NAME:-ecs-demo-sa-local}
    export EXTERNAL_ECS_SERVICE_ACCOUNT_NAME=${EXTERNAL_ECS_SERVICE_ACCOUNT_NAME:-ecs-demo-sa-external}
    
    echo "Configuration:"
    echo "  Cluster Name: ${CLUSTER_NAME}"
    echo "  Local Service Account: ${LOCAL_ECS_SERVICE_ACCOUNT_NAME}"
    echo "  External Service Account: ${EXTERNAL_ECS_SERVICE_ACCOUNT_NAME}"
    echo ""
}

# Save service account names to config file
save_to_config() {
    echo -e "${BLUE}Saving service account names to configuration...${NC}"
    
    # Remove any existing section generated by this script
    if grep -q "# === Generated by create-k8s-namespaces-3-clusters.sh" "$CONFIG_FILE" 2>/dev/null; then
        sed '/# === Generated by create-k8s-namespaces-3-clusters.sh/,/^$/d' "$CONFIG_FILE" > "${CONFIG_FILE}.tmp"
        mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
    fi
    
    # Append service account names
    cat >> "$CONFIG_FILE" <<EOF

# === Generated by create-k8s-namespaces-3-clusters.sh on $(date) ===
export LOCAL_ECS_SERVICE_ACCOUNT_NAME="$LOCAL_ECS_SERVICE_ACCOUNT_NAME"
export EXTERNAL_ECS_SERVICE_ACCOUNT_NAME="$EXTERNAL_ECS_SERVICE_ACCOUNT_NAME"

EOF
    
    echo "✓ Service account names appended to: $CONFIG_FILE"
    echo ""
}

# Function to create namespace for a cluster
create_namespace_for_cluster() {
    local cluster_num=$1
    local task_role_arn=$2
    local svc_account_name=$3
    local account_type=$4
    
    local namespace="ecs-${CLUSTER_NAME}-${cluster_num}"
    
    echo -e "${GREEN}Creating namespace for cluster ${cluster_num} (${account_type})...${NC}"
    
    # Create namespace
    kubectl create ns ${namespace} 2>/dev/null || echo "  Namespace ${namespace} already exists"
    
    # Label namespace for ambient mode
    kubectl label namespace ${namespace} istio.io/dataplane-mode=ambient --overwrite
    echo "  ✓ Namespace labeled for ambient mode"
    
    # Create service account
    kubectl create sa ${svc_account_name} -n ${namespace} 2>/dev/null || echo "  Service account ${svc_account_name} already exists"
    
    # Annotate service account with task role ARN (remove /ecs/ambient prefix)
    local clean_role_arn=$task_role_arn
    kubectl -n ${namespace} annotate sa ${svc_account_name} \
        ecs.solo.io/role-arn=${clean_role_arn} \
        --overwrite
    
    echo "  ✓ Service account annotated with role ARN"
    echo "    Namespace: ${namespace}"
    echo "    Service Account: ${svc_account_name}"
    echo "    Role ARN: ${clean_role_arn}"
    echo ""
}

# Main execution
main() {
    parse_options "$@"
    load_config
    validate_env
    set_service_account_names
    
    echo -e "${BLUE}Creating namespaces for LOCAL clusters (1 and 2)...${NC}"
    echo ""
    
    # Create namespaces for local clusters
    create_namespace_for_cluster "1" "$LOCAL_TASK_ROLE_ARN" "$LOCAL_ECS_SERVICE_ACCOUNT_NAME" "local"
    create_namespace_for_cluster "2" "$LOCAL_TASK_ROLE_ARN" "$LOCAL_ECS_SERVICE_ACCOUNT_NAME" "local"
    
    echo -e "${BLUE}Creating namespace for EXTERNAL cluster (3)...${NC}"
    echo ""
    
    # Create namespace for external cluster
    create_namespace_for_cluster "3" "$EXTERNAL_TASK_ROLE_ARN" "$EXTERNAL_ECS_SERVICE_ACCOUNT_NAME" "external"
    
    # Save service account names to config
    save_to_config
    
    echo -e "${GREEN}=============================================${NC}"
    echo -e "${GREEN}  Namespace Setup Complete!${NC}"
    echo -e "${GREEN}=============================================${NC}"
    echo ""
    echo "Created namespaces:"
    echo "  - ecs-${CLUSTER_NAME}-1 (local)"
    echo "  - ecs-${CLUSTER_NAME}-2 (local)"
    echo "  - ecs-${CLUSTER_NAME}-3 (external)"
    echo ""
    echo "Service account names saved to: $CONFIG_FILE"
    echo ""
    echo "Verify with:"
    echo "  kubectl get ns | grep ecs-${CLUSTER_NAME}"
    echo "  kubectl get sa -n ecs-${CLUSTER_NAME}-1"
    echo ""
}

# Run main function
main "$@"

# ============================================
# CLEANUP - Prevents shell pollution
# ============================================
# This section ensures that when the script is sourced (. script.sh),
# only the exported service account names remain in the shell environment.

# Unset all functions
unset -f parse_options
unset -f load_config
unset -f validate_env
unset -f set_service_account_names
unset -f save_to_config
unset -f create_namespace_for_cluster
unset -f main

# Unset internal variables (keep only exports: LOCAL_ECS_SERVICE_ACCOUNT_NAME, EXTERNAL_ECS_SERVICE_ACCOUNT_NAME)
unset GREEN BLUE YELLOW NC

# Reset shell options
set +e

# Note: LOCAL_ECS_SERVICE_ACCOUNT_NAME and EXTERNAL_ECS_SERVICE_ACCOUNT_NAME remain exported
